--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:33,138] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:33] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:37,348] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:37] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:39,346] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:39] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:40,619] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:40] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:48,107] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:48] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
--------------------------------------------------------------------------------
ERROR    [2016-01-01 18:19:52,628] : cherrypy.error.140021944608472 : from line (216) at
	/usr/lib/python3.4/site-packages/cherrypy/_cplogging.py
	--
	[01/Jan/2016:18:19:52] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 289, in api
    return handler(**handler_args)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 422, in api_fetchalbumart
    img_data = self.albumartcache_load(b64imgpath)
  File "/usr/lib/python3.4/site-packages/cherrymusicserver/httphandler.py", line 463, in albumartcache_load
    with open(imgb64path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.local/share/cherrymusic/albumart'
